"""added temporary potion table

Revision ID: c417c6efe2f8
Revises: 243c96c62be4
Create Date: 2019-02-24 21:44:55.539863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c417c6efe2f8'
down_revision = '243c96c62be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('potion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('cost', sa.String(length=120), nullable=True),
    sa.Column('rarity', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_potion_cost'), 'potion', ['cost'], unique=False)
    op.create_index(op.f('ix_potion_name'), 'potion', ['name'], unique=True)
    op.create_index(op.f('ix_potion_timestamp'), 'potion', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_potion_timestamp'), table_name='potion')
    op.drop_index(op.f('ix_potion_name'), table_name='potion')
    op.drop_index(op.f('ix_potion_cost'), table_name='potion')
    op.drop_table('potion')
    # ### end Alembic commands ###
